/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JtotusSetPasswordsGUI.java
 *
 * Created on Jan 1, 2011, 1:34:06 PM
 */

package org.jtotus.gui.passwords;

import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import org.jtotus.config.ConfigLoader;
import org.jtotus.config.GUIConfig;

/**
 *
 * @author house
 */
public class JtotusSetPasswordsGUI extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    

    /** Creates new form JtotusSetPasswordsGUI */
    public JtotusSetPasswordsGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
       
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gmailLoginTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gmailPasswordTextField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        brokerLoginTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brokerPasswordTextField = new javax.swing.JPasswordField();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.jtotus.gui.JtotusApp.class).getContext().getResourceMap(JtotusSetPasswordsGUI.class);
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        gmailLoginTextField.setText(resourceMap.getString("gmailLoginTextField.text")); // NOI18N
        gmailLoginTextField.setName("gmailLoginTextField"); // NOI18N
        gmailLoginTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmailLoginTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(gmailLoginTextField);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        gmailPasswordTextField.setText(resourceMap.getString("gmailPasswordTextField.text")); // NOI18N
        gmailPasswordTextField.setName("gmailPasswordTextField"); // NOI18N
        gmailPasswordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmailPasswordTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(gmailPasswordTextField);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3);

        brokerLoginTextField.setText(resourceMap.getString("brokerLoginTextField.text")); // NOI18N
        brokerLoginTextField.setName("brokerLoginTextField"); // NOI18N
        brokerLoginTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brokerLoginTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(brokerLoginTextField);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);

        brokerPasswordTextField.setText(resourceMap.getString("brokerPasswordTextField.text")); // NOI18N
        brokerPasswordTextField.setName("brokerPasswordTextField"); // NOI18N
        brokerPasswordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brokerPasswordTextFieldMouseClicked(evt);
            }
        });
        jPanel1.add(brokerPasswordTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void gmailPasswordTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailPasswordTextFieldMouseClicked
        gmailPasswordTextField.setText("");
    }//GEN-LAST:event_gmailPasswordTextFieldMouseClicked

    private void brokerPasswordTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brokerPasswordTextFieldMouseClicked
        brokerPasswordTextField.setText("");
    }//GEN-LAST:event_brokerPasswordTextFieldMouseClicked

    private void brokerLoginTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brokerLoginTextFieldMouseClicked
        brokerLoginTextField.setText("");
    }//GEN-LAST:event_brokerLoginTextFieldMouseClicked

    private void gmailLoginTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailLoginTextFieldMouseClicked
        gmailLoginTextField.setText("");
    }//GEN-LAST:event_gmailLoginTextFieldMouseClicked

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
         this.processWindowEvent(
            new WindowEvent(
                  this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelButtonMousePressed

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        String forComparison = null;
        //Store Password
        ConfigLoader<GUIConfig> loader = new ConfigLoader<GUIConfig>("GUIConfig");
        GUIConfig config = loader.getConfig();
        
        forComparison = brokerLoginTextField.getText();
        if (!forComparison.equals("Login") && forComparison.length() != 0){
            config.setBrokerLogin(forComparison);
        }

        forComparison = new String(brokerPasswordTextField.getPassword()).trim();
        if (!forComparison.equals("Password") && forComparison.length() != 0){
            config.setBrokerPassword(forComparison);
        }


        forComparison = gmailLoginTextField.getText();
        if (!forComparison.equals("Login") && forComparison.length() != 0){
            config.setGmailLogin(forComparison);
        }

        forComparison = new String(gmailPasswordTextField.getPassword()).trim();;
        if (!forComparison.equals("Password") && forComparison.length() != 0){
            config.setGmailPassword(forComparison);
        }
        
        

        loader.storeConfig(config);
        
        System.out.println("GUIConfig is updated\n");
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonMouseClicked

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JtotusSetPasswordsGUI dialog = new JtotusSetPasswordsGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void doShow() {
       this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brokerLoginTextField;
    private javax.swing.JPasswordField brokerPasswordTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField gmailLoginTextField;
    private javax.swing.JPasswordField gmailPasswordTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
